// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OYyVgRXDh6l50P5Km33fhlC2752VqFM',
    appId: '1:57761475438:web:950bc7c93239d56302af7f',
    messagingSenderId: '57761475438',
    projectId: 'focusmate-ea9fc',
    authDomain: 'focusmate-ea9fc.firebaseapp.com',
    storageBucket: 'focusmate-ea9fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCER2AcU0U2pGUjRnPFbnyAhOVzhQttblg',
    appId: '1:57761475438:android:17c5bba63aae753302af7f',
    messagingSenderId: '57761475438',
    projectId: 'focusmate-ea9fc',
    storageBucket: 'focusmate-ea9fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwv3vAjji5WHv75y_Gt83cgJ0iWghD7B4',
    appId: '1:57761475438:ios:971c35b19adf3aec02af7f',
    messagingSenderId: '57761475438',
    projectId: 'focusmate-ea9fc',
    storageBucket: 'focusmate-ea9fc.firebasestorage.app',
    iosBundleId: 'com.example.focusMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwv3vAjji5WHv75y_Gt83cgJ0iWghD7B4',
    appId: '1:57761475438:ios:971c35b19adf3aec02af7f',
    messagingSenderId: '57761475438',
    projectId: 'focusmate-ea9fc',
    storageBucket: 'focusmate-ea9fc.firebasestorage.app',
    iosBundleId: 'com.example.focusMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2OYyVgRXDh6l50P5Km33fhlC2752VqFM',
    appId: '1:57761475438:web:950bc7c93239d56302af7f',
    messagingSenderId: '57761475438',
    projectId: 'focusmate-ea9fc',
    authDomain: 'focusmate-ea9fc.firebaseapp.com',
    storageBucket: 'focusmate-ea9fc.firebasestorage.app',
  );
}
